[package]
name = "zellij-tab-namer"
version = "0.3.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5"
zellij-tile = "=0.44.0"

[[bin]]
name = "zellij-tab-namer"
path = "rust/src/main.rs"
test = false

[lib]
name = "zellij_tab_namer_plugin"
path = "rust/src/lib.rs"

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = "s"
